services:
  gazebo:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: gazebo-vnc-gui
    ports:
      - "8080:8080"  # NoVNC web interface
      - "5901:5901"  # VNC server
    volumes:
      # Mount local volume for Gazebo worlds/models
      - ./docker/robots/worlds:/opt/simulation/robots/worlds
      - ./docker/robots:/opt/simulation/robots
      # Optional: Mount custom world files from host
      - ./custom_worlds:/opt/simulation/custom_worlds:ro
    environment:
      - DISPLAY=:1
      - VNC_PASSWORD=gazebo
    restart: unless-stopped
    # Increase shared memory for GUI applications
    shm_size: 512m
    # Security options for GUI applications
    security_opt:
      - seccomp:unconfined
    # Capabilities needed for VNC/X11
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true